apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "capstone-chart-vulnerable-python.fullname" . }}
  labels:
    app: {{ include "capstone-chart-vulnerable-python.name" . }}
    chart: {{ include "capstone-chart-vulnerable-python.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "capstone-chart-vulnerable-python.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "capstone-chart-vulnerable-python.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: python
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.containers.ports.containerPort }}
        env:
           {{- toYaml .Values.env | nindent 8 }}
        resources:
           {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: python-config
        configMap:
          name: python-config