apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "capstone-chart-vulnerable-python.fullname" . }}-route
  namespace: {{ .Release.Namespace }}
  annotations:
    konghq.com/strip-path: 'true'
spec:
  ingressClassName: kong
  rules:
    - http:
        paths:
          - path: /python
            pathType: Exact
            backend:
              service:
                name: {{ include "capstone-chart-vulnerable-python.fullname" . }}-nginx
                port:
                  number: 80