apiVersion: v1
kind: Service
metadata:
  name: {{ include "capstone-chart-vulnerable-python.name" . }}
  labels:
    app: {{ include "capstone-chart-vulnerable-python.name" . }}
    chart: {{ include "capstone-chart-vulnerable-python.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: {{ .Values.service.protocol }}
  selector:
    app: {{ include "capstone-chart-vulnerable-python.name" . }}
    release: {{ .Release.Name }}
