apiVersion: v1
kind: Service
metadata:
  name: python
  labels:
    app: {{ include "capstone-chart-vulnerable-python.name" . }}
    chart: {{ include "capstone-chart-vulnerable-python.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.python.service.type }}
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: {{ include "capstone-chart-vulnerable-python.name" . }}
    release: {{ .Release.Name }}
